#! /bin/bash 
read x
echo -e "Student \t Test1 \t Test2 \t Average"
test1=0
test2 =0
cnt=0
average=0
while read x
do
	student=`echo $x | cut -d ";" -f 1`
	a=`echo $x | cut -d ";" -f 2`
	b=`echo $x | cut -d ";" -f 3`
	let sum=test1+test2
	let average=sum/2
	echo -e $student\\t$a\\t$b\\t$average
	let test1=test1+a
	let test2=test2+b
	let cnt=cnt+1
done
let average=test1/cnt
echo -e "Average: \t $average" 
